import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link';

import Button from '../components/button';

export default function About() {
  return (
    <div className={styles.container}>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          About Page
        </h1>
        <Link href="/">Index</Link>
        <Button />
      </main>
    </div>
  )
}