import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link';

import { useRequest } from '../hooks/useRequest';

export default function Home() {

  const { data, error } = useRequest('users/' + 1);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Home
        </h1>
        <Link href="/details">
          <a>Details</a>
        </Link>
        {data &&
          <div>
            User name: {data.name}
          </div>
        }
      </main>
    </div>
  )
}
